# Generated by Django 6.0 on 2026-01-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to hide these details site-wide')),
            ],
            options={
                'verbose_name': 'Church Bank Detail',
            },
        ),
    ]
