# Generated by Django 6.0 on 2026-01-12 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0009_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('series_name', models.CharField(blank=True, help_text='e.g., The Overflow Series', max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='sermons/thumbnails/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube link')),
                ('audio_url', models.URLField(blank=True, help_text='Telegram audio link')),
                ('duration', models.CharField(help_text='e.g., 45 Mins', max_length=20)),
                ('date_preached', models.DateField()),
                ('status', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid/Buy')], default='free', max_length=10)),
                ('store_url', models.URLField(blank=True, help_text='Link to purchase page if paid')),
                ('is_trending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.branch')),
                ('preacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.leader')),
            ],
            options={
                'ordering': ['-date_preached'],
            },
        ),
    ]
