# Generated by Django 6.0 on 2026-01-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Set price if status is Paid', max_digits=10),
        ),
    ]
