# Generated by Django 6.0 on 2026-01-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0002_sermon_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='resources/thumbnails/')),
                ('status', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid/Buy')], default='free', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(default='GOGAP Publications', max_length=255)),
                ('book_type', models.CharField(choices=[('ebook', 'E-Book (Digital)'), ('physical', 'Physical Copy')], default='ebook', max_length=20)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Upload PDF if the book is free', null=True, upload_to='books/pdfs/')),
                ('external_purchase_link', models.URLField(blank=True, help_text='Link to Amazon/Other store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='store_url',
        ),
        migrations.AlterField(
            model_name='sermon',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='thumbnail',
            field=models.ImageField(upload_to='resources/thumbnails/'),
        ),
    ]
