# Generated by Django 6.0.2 on 2026-02-12 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0004_alter_book_description_alter_sermon_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SermonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Sermon Categories',
            },
        ),
        migrations.AddField(
            model_name='sermon',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Upload audio file for direct download', null=True, upload_to='sermons/audios/'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='theme',
            field=models.CharField(blank=True, help_text='The theme of the sermon/series', max_length=255),
        ),
        migrations.AddField(
            model_name='sermon',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file if not using YouTube', null=True, upload_to='sermons/videos/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Telegram audio link (optional if uploading audio)'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube link (optional if uploading video)'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sermons.sermoncategory'),
        ),
    ]
