# Generated by Django 6.0 on 2026-04-14 10:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0024_presidingpastor_medium_url'),
        ('sermons', '0005_sermoncategory_sermon_audio_file_sermon_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='is_live_recording',
            field=models.BooleanField(default=False, help_text='Automatically set to True when created from a live broadcast recording.'),
        ),
        migrations.CreateModel(
            name='AudioBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Sunday Celebration Service', max_length=255)),
                ('stream_key', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Auto-generated. Use this as your OBS stream key.', unique=True)),
                ('hls_stream_url', models.URLField(blank=True, help_text='Paste your HLS stream URL (.m3u8) from your media server (nginx-rtmp, Cloudflare, etc.)')),
                ('is_live', models.BooleanField(default=False, help_text="Toggle ON to start broadcasting. The 'Listen Live' player will appear on the site.")),
                ('last_broadcast_end', models.DateTimeField(blank=True, help_text="Automatically set when you toggle 'is_live' off.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preacher', models.ForeignKey(blank=True, help_text='Who is preaching this session?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.leader')),
            ],
            options={
                'verbose_name': 'Audio Broadcast',
                'verbose_name_plural': 'Audio Broadcasts',
                'ordering': ['-created_at'],
            },
        ),
    ]
