# Generated by Django 6.0 on 2026-02-02 10:50

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Brief description of the event', verbose_name='Content'),
        ),
    ]
