# Generated by Django 6.0.2 on 2026-02-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='amazon_link',
            field=models.URLField(blank=True, help_text='Link to Amazon store', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in Dollars ($)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sellar_link',
            field=models.URLField(blank=True, help_text='Link to Sellar store', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sellar_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in Naira (₦)', max_digits=10),
        ),
    ]
