# Generated by Django 6.0.2 on 2026-02-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_price_product_amazon_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='sellar_price',
            field=models.DecimalField(decimal_places=2, help_text='Price in Naira (₦)', max_digits=10),
        ),
    ]
