# Generated by Django 6.0 on 2026-01-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Have a prayer request? Want to learn more about our community? Our heart is open to you.')),
            ],
            options={
                'verbose_name': 'Contact Page Setting',
                'verbose_name_plural': 'Contact Page Settings',
            },
        ),
    ]
