# Generated by Django 6.0 on 2026-01-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactpagesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPageSettings',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='is_main_branch',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='name',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
