# Generated by Django 6.0 on 2026-01-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_delete_contactpagesettings_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
