# Generated by Django 6.0 on 2026-02-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Facebook Page URL', null=True)),
                ('youtube', models.URLField(blank=True, help_text='YouTube Channel URL', null=True)),
                ('mixlr', models.URLField(blank=True, help_text='Mixlr URL', null=True)),
                ('telegram', models.URLField(blank=True, help_text='Telegram Channel URL', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Instagram Profile URL', null=True)),
                ('x_twitter', models.URLField(blank=True, help_text='X (Twitter) Profile URL', null=True, verbose_name='X (Twitter)')),
                ('google_map_embed', models.TextField(blank=True, help_text='Paste the Google Maps Embed HTML code here (iframe)', null=True)),
            ],
            options={
                'verbose_name': 'Contact Page Settings',
                'verbose_name_plural': 'Contact Page Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('testimony_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonies',
            },
        ),
    ]
