# Generated by Django 6.0 on 2026-02-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_contactpagesettings_testimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpagesettings',
            name='google_map_link',
            field=models.URLField(blank=True, help_text='Link to open location in Google Maps (optional)', null=True),
        ),
        migrations.AddField(
            model_name='contactpagesettings',
            name='social_media_section_description',
            field=models.TextField(default='Stay connected with TVA on social media. Follow us for live updates, sermons, and daily inspiration.'),
        ),
        migrations.AddField(
            model_name='contactpagesettings',
            name='social_media_section_heading',
            field=models.CharField(default='Join Our Online Community', help_text='Main heading', max_length=200),
        ),
        migrations.AddField(
            model_name='contactpagesettings',
            name='social_media_section_title',
            field=models.CharField(default='Connect With Us', help_text='Small title above the heading', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpagesettings',
            name='testimony_section_description',
            field=models.TextField(default="Your testimony can be the key to someone else's breakthrough. Share what the Lord has done in your life."),
        ),
        migrations.AddField(
            model_name='contactpagesettings',
            name='testimony_section_heading',
            field=models.CharField(default='Has God been good to you?', help_text='Main heading', max_length=200),
        ),
        migrations.AddField(
            model_name='contactpagesettings',
            name='testimony_section_title',
            field=models.CharField(default='Share Your Story', help_text='Small title above the heading', max_length=100),
        ),
    ]
