# Generated by Django 6.0 on 2026-02-02 10:50

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_contactpagesettings_google_map_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpagesettings',
            name='social_media_section_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Stay connected with TVA on social media. Follow us for live updates, sermons, and daily inspiration.', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='contactpagesettings',
            name='testimony_section_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default="Your testimony can be the key to someone else's breakthrough. Share what the Lord has done in your life.", verbose_name='Content'),
        ),
    ]
