# Generated by Django 6.0 on 2026-01-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='sermons/')),
                ('date', models.DateField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('video_url', models.URLField(blank=True, help_text='Link to the sermon video', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
