# Generated by Django 6.0 on 2026-01-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200)),
                ('image_file', models.ImageField(blank=True, help_text='Upload an image from your computer', null=True, upload_to='gallery/')),
                ('external_url', models.URLField(blank=True, help_text='Or paste a link from the internet (e.g., Unsplash)', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order to display images')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
