# Generated by Django 6.0 on 2026-01-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(help_text='e.g., Main Sanctuary or North Branch', max_length=100)),
                ('sunday_service_1', models.CharField(default='Empowerment: 8:00 AM', max_length=100)),
                ('sunday_service_2', models.CharField(default='Celebration: 10:30 AM', max_length=100)),
                ('midweek_service', models.CharField(default='Wednesday Word: 6:00 PM', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Church Branches',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.TextField(default='"A garden where souls are nurtured by grace..."')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('copyright_text', models.CharField(default='Garden of Grace and Prayer Sanctuary. All rights reserved.', max_length=255)),
            ],
            options={
                'verbose_name': 'Footer Setting',
            },
        ),
    ]
