# Generated by Django 6.0 on 2026-02-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_churchbranch_footersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='About Us', max_length=100)),
                ('title', models.CharField(help_text="Use <br> for line breaks and <span class='text-secondary italic'>Text</span> for styled text", max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about_section/')),
                ('button_text', models.CharField(default='Discover Our Mission', max_length=50)),
                ('button_url', models.CharField(default='/about/', max_length=255)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Sermon',
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='copyright_text',
            field=models.CharField(default='The Vineyard Assembly. All rights reserved.', max_length=255),
        ),
    ]
