# Generated by Django 6.0 on 2026-02-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_aboutsection_delete_event_delete_sermon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='Rooted & Grounded', max_length=100)),
                ('title', models.CharField(help_text="Use <br> for line breaks and <span class='text-secondary italic'>Text</span> for styled text", max_length=255)),
            ],
            options={
                'verbose_name': 'Experience Header',
                'verbose_name_plural': 'Experience Header',
            },
        ),
        migrations.CreateModel(
            name='ExperienceValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon_name', models.CharField(help_text='Enter Lucide icon name (e.g., flame, book-open, users)', max_length=50)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Experience Value',
                'verbose_name_plural': 'Experience Values',
                'ordering': ['order'],
            },
        ),
    ]
