# Generated by Django 6.0 on 2026-02-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_experienceheader_experiencevalue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExperienceValue',
            new_name='CoreValue',
        ),
        migrations.DeleteModel(
            name='ExperienceHeader',
        ),
        migrations.AlterModelOptions(
            name='corevalue',
            options={'ordering': ['order'], 'verbose_name': 'Core Value', 'verbose_name_plural': 'Core Values'},
        ),
    ]
