# Generated by Django 6.0 on 2026-02-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_rename_experiencevalue_corevalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Our Store', max_length=100)),
                ('title', models.CharField(help_text="Use <br> for line breaks and <span class='text-secondary italic'>Text</span> for styled text", max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='store_section/')),
                ('feature1_title', models.CharField(default='Books', max_length=100)),
                ('feature1_text', models.CharField(default='In-depth study guides', max_length=255)),
                ('feature2_title', models.CharField(default='Courses/Apparel', max_length=100)),
                ('feature2_text', models.CharField(default='TVA Merchandise', max_length=255)),
                ('button_text', models.CharField(default='Visit the Store', max_length=50)),
                ('button_url', models.CharField(default='/store/', max_length=255)),
            ],
            options={
                'verbose_name': 'Store Section',
                'verbose_name_plural': 'Store Section',
            },
        ),
    ]
