# Generated by Django 6.0 on 2026-02-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_storesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Upcoming Events & News', max_length=255)),
            ],
            options={
                'verbose_name': 'Events Header',
                'verbose_name_plural': 'Events Header',
            },
        ),
        migrations.CreateModel(
            name='FeaturedQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author_label', models.CharField(default='TVA Mandate', max_length=100)),
            ],
            options={
                'verbose_name': 'Featured Quote',
                'verbose_name_plural': 'Featured Quote',
            },
        ),
        migrations.CreateModel(
            name='GivingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Partner with the Vision', max_length=255)),
                ('description', models.TextField()),
                ('button_text', models.CharField(default='Give Online', max_length=100)),
                ('button_url', models.CharField(default='/offering/', max_length=255)),
            ],
            options={
                'verbose_name': 'Giving Section',
                'verbose_name_plural': 'Giving Section',
            },
        ),
        migrations.CreateModel(
            name='PastorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='Our Shepherd', max_length=100)),
                ('name', models.CharField(default='Pastor Adeyinka', max_length=255)),
                ('quote', models.TextField(help_text='The italicized quote')),
                ('description', models.TextField(help_text='The main bio description')),
                ('image', models.ImageField(upload_to='pastor_section/')),
                ('button_text', models.CharField(default='Read Full Bio', max_length=100)),
                ('button_url', models.CharField(default='/about/', max_length=255)),
            ],
            options={
                'verbose_name': 'Pastor Section',
                'verbose_name_plural': 'Pastor Section',
            },
        ),
    ]
