# Generated by Django 6.0 on 2026-02-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_eventsheader_featuredquote_givingsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='live_stream_button_text',
            field=models.CharField(blank=True, default='Watch Live', help_text='Text for the live stream button', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='live_stream_url',
            field=models.URLField(blank=True, help_text='URL for the live stream (e.g., YouTube Link). Leave empty to hide button.', null=True),
        ),
    ]
