# Generated by Django 6.0 on 2026-02-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_alter_aboutsection_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastorsection',
            options={'ordering': ['order'], 'verbose_name': 'Pastor Section', 'verbose_name_plural': 'Pastor Section'},
        ),
        migrations.AddField(
            model_name='pastorsection',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
