# Generated by Django 6.0 on 2026-01-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Story & Vision', max_length=200)),
                ('subtitle', models.CharField(default='Who We Are', max_length=100)),
                ('main_image', models.ImageField(upload_to='about/')),
                ('established_year', models.CharField(default='Est. 2012', max_length=20)),
                ('established_text', models.CharField(default='A Decade of Grace', max_length=100)),
                ('description', models.TextField()),
                ('mission_title', models.CharField(default='Our Mission', max_length=100)),
                ('mission_text', models.TextField()),
                ('vision_title', models.CharField(default='Our Vision', max_length=100)),
                ('vision_text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'About Section',
            },
        ),
    ]
