# Generated by Django 6.0 on 2026-01-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='mission_description',
            field=models.TextField(default='To cultivate a global garden...'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_subtitle',
            field=models.CharField(default='Our Purpose', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_description',
            field=models.TextField(default="To see the fragrance of God's presence..."),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_subtitle',
            field=models.CharField(default='Our Future', max_length=100),
        ),
    ]
