# Generated by Django 6.0 on 2026-01-11 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutsection_mission_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255)),
                ('location_label', models.CharField(default='Global Grace Headquarters', max_length=255)),
                ('address_url', models.URLField(blank=True, help_text='Google Maps link', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='BranchActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Sunday Service or Midweek Service', max_length=100)),
                ('time_slots', models.TextField(help_text='Enter times, one per line (e.g., 8:00 AM - 10:00 AM)')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='about.branch')),
            ],
        ),
    ]
