# Generated by Django 6.0 on 2026-01-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_branch_branchactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon_name', models.CharField(help_text='Enter Lucide icon name (e.g., flame, book-open, users, heart)', max_length=50)),
                ('description', models.TextField()),
                ('color_scheme', models.CharField(choices=[('secondary', 'Green (Secondary)'), ('accent', 'Gold (Accent)'), ('primary', 'Blue (Primary)')], default='primary', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Set priority order')),
            ],
            options={
                'verbose_name_plural': 'Core Values',
                'ordering': ['order'],
            },
        ),
    ]
