# Generated by Django 6.0 on 2026-01-11 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_corevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(help_text='e.g., Senior Pastor, Resident Pastor', max_length=255)),
                ('image', models.ImageField(upload_to='leaders/')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaders', to='about.branch')),
            ],
            options={
                'verbose_name_plural': 'Leadership',
                'ordering': ['order'],
            },
        ),
    ]
