# Generated by Django 6.0 on 2026-01-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeliefPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='aboutsection',
            options={},
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='established_text',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='established_year',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='mission_description',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='mission_subtitle',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='mission_text',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='mission_title',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='title',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='vision_description',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='vision_subtitle',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='vision_text',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='vision_title',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='doctrine_pdf',
            field=models.FileField(blank=True, help_text='Upload the Statement of Faith PDF', null=True, upload_to='doctrines/'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='sof_description',
            field=models.TextField(default='Our beliefs are rooted in...'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='sof_subtitle',
            field=models.CharField(default='Foundations', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='sof_title',
            field=models.CharField(default='Statement of Faith', max_length=100),
        ),
    ]
