# Generated by Django 6.0 on 2026-01-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_beliefpoint_alter_aboutsection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementOfFaith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sof_subtitle', models.CharField(default='Foundations', max_length=100)),
                ('sof_title', models.CharField(default='Statement of Faith', max_length=100)),
                ('sof_description', models.TextField(default='Our beliefs are rooted in...')),
                ('doctrine_pdf', models.FileField(blank=True, null=True, upload_to='doctrines/')),
            ],
            options={
                'verbose_name_plural': 'Statement of Faith (Header)',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name_plural': 'About Section'},
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='doctrine_pdf',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='sof_description',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='sof_subtitle',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='sof_title',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='established_text',
            field=models.CharField(default='A Decade of Grace', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='established_year',
            field=models.CharField(default='Est. 2012', max_length=20),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_description',
            field=models.TextField(default='To cultivate a global garden...'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_subtitle',
            field=models.CharField(default='Our Purpose', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_title',
            field=models.CharField(default='Our Mission', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='subtitle',
            field=models.CharField(default='Who We Are', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(default='Our Story & Vision', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_description',
            field=models.TextField(default="To see the fragrance of God's presence..."),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_subtitle',
            field=models.CharField(default='Our Future', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_title',
            field=models.CharField(default='Our Vision', max_length=100),
        ),
        migrations.AlterField(
            model_name='beliefpoint',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='icon_name',
            field=models.CharField(help_text='Enter Lucide icon name', max_length=50),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leader',
            name='position',
            field=models.CharField(max_length=255),
        ),
    ]
