# Generated by Django 6.0 on 2026-01-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_statementoffaith_alter_aboutsection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='Enter the year (e.g., 2012)', max_length=4)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Used to arrange events in order')),
            ],
            options={
                'verbose_name_plural': 'History Milestones',
                'ordering': ['year', 'order'],
            },
        ),
    ]
