# Generated by Django 6.0 on 2026-01-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_historymilestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='e.g., 15+ or 500+', max_length=20)),
                ('label', models.CharField(help_text='e.g., Ministries or Members', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order from left to right')),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'ordering': ['order'],
            },
        ),
    ]
