# Generated by Django 6.0 on 2026-02-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='doctrine_pdf',
            field=models.FileField(blank=True, null=True, upload_to='doctrines/'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='sof_description',
            field=models.TextField(default='Our beliefs are rooted in the statement of faith we profess.'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='sof_subtitle',
            field=models.CharField(default='Foundations', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='sof_title',
            field=models.CharField(default='Statement of Faith', max_length=100),
        ),
    ]
