# Generated by Django 6.0 on 2026-02-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_aboutsection_doctrine_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='doctrine_pdf',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='sof_description',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='sof_subtitle',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='sof_title',
        ),
    ]
