# Generated by Django 6.0 on 2026-02-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_remove_aboutsection_doctrine_pdf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name_plural': '0. About Page (Story/Vision/Mission)'},
        ),
        migrations.AlterModelOptions(
            name='beliefpoint',
            options={'ordering': ['order'], 'verbose_name_plural': '2. Belief Points (Cards)'},
        ),
        migrations.AlterModelOptions(
            name='statementoffaith',
            options={'verbose_name': 'Doctrine & Statement of Faith', 'verbose_name_plural': '1. Statement of Faith (Doctrine Upload)'},
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='doctrine_pdf',
            field=models.FileField(blank=True, null=True, upload_to='doctrines/', verbose_name='Doctrine File (UPLOAD HERE)'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='sof_description',
            field=models.TextField(default='Our beliefs are rooted in the statement of faith we profess.', verbose_name='Faith Description'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='sof_subtitle',
            field=models.CharField(default='Foundations', max_length=100, verbose_name='Section Subtitle'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='sof_title',
            field=models.CharField(default='Statement of Faith', max_length=100, verbose_name='Section Title'),
        ),
    ]
