# Generated by Django 6.0 on 2026-02-01 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_alter_aboutsection_options_alter_beliefpoint_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='doctrine_pdf',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='sof_description',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='sof_subtitle',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='sof_title',
        ),
    ]
