# Generated by Django 6.0 on 2026-02-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_remove_aboutsection_doctrine_pdf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name_plural': 'About Section (Main)'},
        ),
        migrations.AlterModelOptions(
            name='beliefpoint',
            options={'ordering': ['order'], 'verbose_name_plural': 'Belief Points (Cards)'},
        ),
        migrations.AlterModelOptions(
            name='statementoffaith',
            options={'verbose_name': 'Doctrine & Statement of Faith', 'verbose_name_plural': 'Statement of Faith (Doctrine)'},
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='foundation_quote',
            field=models.TextField(default='A garden where souls are nurtured by grace and set on fire by the Spirit.', help_text='A short summary or mandate of your founding.'),
        ),
    ]
