# Generated by Django 6.0 on 2026-02-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_alter_aboutsection_options_alter_beliefpoint_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatementOfFaith',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='vision_subtitle',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='doctrine_pdf',
            field=models.FileField(blank=True, null=True, upload_to='doctrines/'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='sof_description',
            field=models.TextField(default='Our beliefs are rooted in...'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='sof_subtitle',
            field=models.CharField(default='Foundations', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='sof_title',
            field=models.CharField(default='Statement of Faith', max_length=100),
        ),
    ]
