# Generated by Django 6.0 on 2026-02-01 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0015_delete_statementoffaith_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beliefpoint',
            name='about_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beliefs', to='about.aboutsection'),
        ),
    ]
