# Generated by Django 6.0 on 2026-02-01 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_beliefpoint_about_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundingPastor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Our Founding Pastor', max_length=200)),
                ('hero_subtitle', models.CharField(default='The Visionary Behind TVA', max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pastors/')),
                ('bio_title', models.CharField(default='His Story', max_length=200)),
                ('bio_content', models.TextField(default='')),
                ('bio_image', models.ImageField(blank=True, null=True, upload_to='pastors/')),
                ('vision_title', models.CharField(default='Founding Vision', max_length=200)),
                ('vision_content', models.TextField(default='')),
                ('legacy_title', models.CharField(default='His Legacy', max_length=200)),
                ('legacy_content', models.TextField(default='')),
                ('quotes_title', models.CharField(default='Words of Wisdom', max_length=200)),
                ('featured_quote', models.TextField(default='')),
                ('quote_author', models.CharField(default='Founding Pastor', max_length=100)),
                ('timeline_title', models.CharField(default='Ministry Timeline', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Founding Pastor Page',
            },
        ),
        migrations.CreateModel(
            name='PastoralTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Our Pastoral Team', max_length=200)),
                ('hero_subtitle', models.CharField(default='Serving Together in Unity', max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pastoral_team/')),
                ('overview_title', models.CharField(default='Meet The Team', max_length=200)),
                ('overview_content', models.TextField(default='')),
                ('structure_title', models.CharField(default='Our Structure', max_length=200)),
                ('structure_content', models.TextField(default='')),
                ('values_title', models.CharField(default='Our Values', max_length=200)),
                ('values_content', models.TextField(default='')),
                ('ministry_title', models.CharField(default='Ministry Areas', max_length=200)),
                ('join_title', models.CharField(default='Join Our Team', max_length=200)),
                ('join_content', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Pastoral Team Page',
            },
        ),
        migrations.CreateModel(
            name='PresidingPastor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Our Presiding Pastor', max_length=200)),
                ('hero_subtitle', models.CharField(default='Leading TVA Today', max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pastors/')),
                ('pastor_name', models.CharField(default='Pastor Name', max_length=200)),
                ('bio_title', models.CharField(default='Meet Our Pastor', max_length=200)),
                ('bio_content', models.TextField(default='')),
                ('bio_image', models.ImageField(blank=True, null=True, upload_to='pastors/')),
                ('vision_title', models.CharField(default='Vision for TVA', max_length=200)),
                ('vision_content', models.TextField(default='')),
                ('focus_title', models.CharField(default='Ministry Focus', max_length=200)),
                ('focus_content', models.TextField(default='')),
                ('message_title', models.CharField(default='A Word From Pastor', max_length=200)),
                ('message_content', models.TextField(default='')),
                ('contact_title', models.CharField(default='Connect With Pastor', max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Presiding Pastor Page',
            },
        ),
        migrations.CreateModel(
            name='PastoralTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='e.g., 2012', max_length=4)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('founding_pastor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='about.foundingpastor')),
            ],
            options={
                'verbose_name_plural': 'Pastoral Timeline Events',
                'ordering': ['year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_members/')),
                ('ministry_area', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('pastoral_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='about.pastoralteam')),
            ],
            options={
                'verbose_name_plural': 'Team Members',
                'ordering': ['order'],
            },
        ),
    ]
