# Generated by Django 6.0 on 2026-02-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0017_foundingpastor_pastoralteam_presidingpastor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundingpastor',
            name='legacy_image',
            field=models.ImageField(blank=True, null=True, upload_to='pastors/'),
        ),
        migrations.AddField(
            model_name='foundingpastor',
            name='quote_image',
            field=models.ImageField(blank=True, null=True, upload_to='pastors/'),
        ),
        migrations.AddField(
            model_name='foundingpastor',
            name='timeline_image',
            field=models.ImageField(blank=True, null=True, upload_to='pastors/'),
        ),
        migrations.AddField(
            model_name='foundingpastor',
            name='vision_image',
            field=models.ImageField(blank=True, null=True, upload_to='pastors/'),
        ),
        migrations.AddField(
            model_name='pastoralteam',
            name='join_image',
            field=models.ImageField(blank=True, null=True, upload_to='pastoral_team/'),
        ),
        migrations.AddField(
            model_name='pastoralteam',
            name='overview_image',
            field=models.ImageField(blank=True, null=True, upload_to='pastoral_team/'),
        ),
        migrations.AddField(
            model_name='pastoralteam',
            name='structure_image',
            field=models.ImageField(blank=True, null=True, upload_to='pastoral_team/'),
        ),
        migrations.AddField(
            model_name='pastoralteam',
            name='values_image',
            field=models.ImageField(blank=True, null=True, upload_to='pastoral_team/'),
        ),
        migrations.AddField(
            model_name='presidingpastor',
            name='focus_image',
            field=models.ImageField(blank=True, null=True, upload_to='pastors/'),
        ),
        migrations.AddField(
            model_name='presidingpastor',
            name='message_image',
            field=models.ImageField(blank=True, null=True, upload_to='pastors/'),
        ),
        migrations.AddField(
            model_name='presidingpastor',
            name='vision_image',
            field=models.ImageField(blank=True, null=True, upload_to='pastors/'),
        ),
    ]
