# Generated by Django 6.0 on 2026-02-02 11:05

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0018_foundingpastor_legacy_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='mission_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='To cultivate a global garden...', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='sof_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Our beliefs are rooted in...', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='vision_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default="To see the fragrance of God's presence...", verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='foundingpastor',
            name='bio_content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='foundingpastor',
            name='legacy_content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='foundingpastor',
            name='vision_content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='pastoralteam',
            name='join_content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='pastoralteam',
            name='overview_content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='pastoralteam',
            name='structure_content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='pastoralteam',
            name='values_content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='presidingpastor',
            name='bio_content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='presidingpastor',
            name='focus_content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='presidingpastor',
            name='message_content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='presidingpastor',
            name='vision_content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
