# Generated by Django 6.0.2 on 2026-02-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0019_alter_aboutsection_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundingpastor',
            name='amazon_book_url',
            field=models.URLField(blank=True, help_text='Link to Amazon author page/book', null=True),
        ),
        migrations.AddField(
            model_name='foundingpastor',
            name='books_title',
            field=models.CharField(default='Books & Resources', max_length=200),
        ),
        migrations.AddField(
            model_name='foundingpastor',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='foundingpastor',
            name='contact_title',
            field=models.CharField(default='Connect With Founding Pastor', max_length=200),
        ),
        migrations.AddField(
            model_name='foundingpastor',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foundingpastor',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foundingpastor',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foundingpastor',
            name='mixlr_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foundingpastor',
            name='selar_book_url',
            field=models.URLField(blank=True, help_text='Link to Selar store/book', null=True),
        ),
        migrations.AddField(
            model_name='foundingpastor',
            name='threads_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foundingpastor',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foundingpastor',
            name='x_url',
            field=models.URLField(blank=True, null=True, verbose_name='X (Twitter) URL'),
        ),
        migrations.AddField(
            model_name='presidingpastor',
            name='amazon_book_url',
            field=models.URLField(blank=True, help_text='Link to Amazon author page/book', null=True),
        ),
        migrations.AddField(
            model_name='presidingpastor',
            name='books_title',
            field=models.CharField(default='Books & Resources', max_length=200),
        ),
        migrations.AddField(
            model_name='presidingpastor',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presidingpastor',
            name='mixlr_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presidingpastor',
            name='selar_book_url',
            field=models.URLField(blank=True, help_text='Link to Selar store/book', null=True),
        ),
        migrations.AddField(
            model_name='presidingpastor',
            name='threads_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presidingpastor',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presidingpastor',
            name='x_url',
            field=models.URLField(blank=True, null=True, verbose_name='X (Twitter) URL'),
        ),
    ]
