# Generated by Django 6.0.2 on 2026-02-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0021_teammember_contact_email_teammember_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
