# Generated by Django 6.0.2 on 2026-02-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0022_leader_contact_email_leader_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundingpastor',
            name='medium_url',
            field=models.URLField(blank=True, help_text='Link to Medium articles', null=True),
        ),
    ]
