# Generated by Django 6.0.2 on 2026-02-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0023_foundingpastor_medium_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidingpastor',
            name='medium_url',
            field=models.URLField(blank=True, help_text='Link to Medium articles', null=True),
        ),
    ]
