# Generated by Django 6.0 on 2026-02-01 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPathwayPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Membership Pathway', max_length=200)),
                ('hero_subtitle', models.CharField(default='Your Journey to Belonging', max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='get_involved/')),
                ('intro_title', models.CharField(default='Discovery Track', max_length=200)),
                ('intro_description', models.TextField(default='We want to help you connect, grow, and serve.')),
            ],
            options={
                'verbose_name': 'Page Configuration',
                'verbose_name_plural': 'Page Configuration',
            },
        ),
        migrations.CreateModel(
            name='PathwayStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='1 to 6', unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='circle', help_text="Lucide icon name (e.g., 'heart', 'users', 'check-circle')", max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='get_involved/steps/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='get_involved.membershippathwaypage')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
