# Generated by Django 6.0 on 2026-02-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0002_churchmembershipregistration_departmentregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityAltar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the City Altar location', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='get_involved/city_altars/')),
                ('leader_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('location', models.CharField(help_text='City or Area (e.g., Ikeja, Lekki)', max_length=100)),
                ('meeting_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Tuesday', max_length=20)),
                ('meeting_time', models.TimeField()),
                ('description', models.TextField(blank=True, help_text='Brief description or welcome message')),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'City Altar / House Fellowship',
                'verbose_name_plural': 'City Altars / House Fellowships',
            },
        ),
    ]
