# Generated by Django 6.0 on 2026-02-02 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0003_cityaltar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fellowship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BOX18', 'Box-18 (Men)'), ('VMUMS', 'V-Mums (Women)'), ('SINGLES', 'Singles & Youths')], max_length=20, unique=True)),
                ('hero_image', models.ImageField(blank=True, help_text='Main banner image for the page', null=True, upload_to='fellowships/')),
                ('about_title', models.CharField(default='About Us', max_length=200)),
                ('about_text', models.TextField(help_text='Detailed information about the fellowship')),
                ('activities_summary', models.TextField(blank=True, help_text='Overview of activities for the year')),
                ('calendar_file', models.FileField(blank=True, help_text='Upload calendar PDF or image', null=True, upload_to='fellowships/calendars/')),
                ('join_info', models.TextField(help_text='Instructions on how new members can join')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Box18Fellowship',
            fields=[
            ],
            options={
                'verbose_name': "Box-18 (Men's Fellowship)",
                'verbose_name_plural': "Box-18 (Men's Fellowship)",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('get_involved.fellowship',),
        ),
        migrations.CreateModel(
            name='SinglesFellowship',
            fields=[
            ],
            options={
                'verbose_name': 'Singles & Youths',
                'verbose_name_plural': 'Singles & Youths',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('get_involved.fellowship',),
        ),
        migrations.CreateModel(
            name='VMumsFellowship',
            fields=[
            ],
            options={
                'verbose_name': "V-Mums (Women's Fellowship)",
                'verbose_name_plural': "V-Mums (Women's Fellowship)",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('get_involved.fellowship',),
        ),
        migrations.CreateModel(
            name='FellowshipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fellowships/events/')),
                ('fellowship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='get_involved.fellowship')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
