# Generated by Django 6.0.2 on 2026-02-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0004_fellowship_box18fellowship_singlesfellowship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='G12Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='G-12 Membership Classes', max_length=200)),
                ('hero_subtitle', models.CharField(default='Your Journey to Leadership and Discipleship', max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='g12/')),
                ('section1_title', models.CharField(default='What is G-12?', max_length=200)),
                ('section1_content', models.TextField(default='')),
                ('section1_image', models.ImageField(blank=True, null=True, upload_to='g12/')),
                ('section2_title', models.CharField(default='Our Vision for You', max_length=200)),
                ('section2_content', models.TextField(default='')),
                ('section2_image', models.ImageField(blank=True, null=True, upload_to='g12/')),
                ('section3_title', models.CharField(default='Class Schedule', max_length=200)),
                ('section3_content', models.TextField(default='')),
                ('section3_image', models.ImageField(blank=True, null=True, upload_to='g12/')),
                ('registration_title', models.CharField(default='Join Our Next Class', max_length=200)),
                ('registration_subtitle', models.TextField(default='Register today to start your journey.')),
            ],
            options={
                'verbose_name': 'G-12 Page Configuration',
                'verbose_name_plural': 'G-12 Page Configuration',
            },
        ),
        migrations.CreateModel(
            name='G12Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('branch', models.CharField(help_text='Your local church branch', max_length=100)),
                ('preferred_class_time', models.CharField(help_text='e.g., Sundays after service, Saturdays 4pm', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'G-12 Registration',
                'verbose_name_plural': 'G-12 Registrations',
            },
        ),
    ]
