# Generated by Django 6.0.2 on 2026-02-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0005_g12page_g12registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityaltar',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code (e.g., +234...)', max_length=20),
        ),
    ]
