# Generated by Django 6.0 on 2026-02-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from name', unique=True)),
                ('card_image', models.ImageField(help_text='Image displayed on the department list.', upload_to='departments/cards/')),
                ('card_summary', models.TextField(help_text='Short description for the card overview.')),
                ('hero_image', models.ImageField(help_text='Large banner image for the department detail page.', upload_to='departments/heroes/')),
                ('content', models.TextField(help_text='Full details about the department (History, activities, etc.)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in the list (lowest first)')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
