# Generated by Django 6.0 on 2026-02-02 10:50

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Full details about the department (History, activities, etc.)', verbose_name='Content'),
        ),
    ]
